server:
  port: 8082

spring:
  kafka:
    bootstrap-servers: 0.0.0.0:29092
  application:
    name: manager-service
  datasource:
    url: jdbc:mysql://localhost:3306/manager-service?user=root&password=test
    name: root
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

resilience4j:
  circuitbreaker:
    instances:
      managerService:
              sliding-window-size: 100
              permitted-number-of-calls-in-half-open-state: 10
              slow-call-duration-threshold:
                seconds: 4
              slow-call-rate-threshold: 90
              failure-rate-threshold: 50
              wait-duration-in-open-state:
                seconds: 10
              minimum-number-of-calls: 10
              sliding-window-type: time_based
