server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
            - Path=/user/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: manager-service
          uri: http://localhost:8082
          predicates:
            - Path=/manager/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: security-service
          uri:
            http://localhost:8083
          predicates:
            - Path=/v1/security


